/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {},
    },
    plugins: [require("daisyui")],
    daisyui: {
        themes: [
            {
                light: {
                    "primary":          "#2563eb",
                    "primary-content":  "#ffffff",
                    "secondary":        "#7c3aed",
                    "secondary-content":"#ffffff",
                    "accent":           "#0891b2",
                    "accent-content":   "#ffffff",
                    "neutral":          "#374151",
                    "neutral-content":  "#f9fafb",
                    "base-100":         "#ffffff",
                    "base-200":         "#f9fafb",
                    "base-300":         "#e5e7eb",
                    "base-content":     "#111827",
                    "info":             "#0ea5e9",
                    "info-content":     "#ffffff",
                    "success":          "#10b981",
                    "success-content":  "#ffffff",
                    "warning":          "#f59e0b",
                    "warning-content":  "#ffffff",
                    "error":            "#ef4444",
                    "error-content":    "#ffffff",
                },
            },
            {
                dark: {
                    "primary":          "#3b82f6",
                    "primary-content":  "#ffffff",
                    "secondary":        "#8b5cf6",
                    "secondary-content":"#ffffff",
                    "accent":           "#06b6d4",
                    "accent-content":   "#ffffff",
                    "neutral":          "#9ca3af",
                    "neutral-content":  "#111827",
                    "base-100":         "#1e2433",
                    "base-200":         "#161d2e",
                    "base-300":         "#0f1520",
                    "base-content":     "#e2e8f0",
                    "info":             "#38bdf8",
                    "info-content":     "#000000",
                    "success":          "#34d399",
                    "success-content":  "#000000",
                    "warning":          "#fbbf24",
                    "warning-content":  "#000000",
                    "error":            "#f87171",
                    "error-content":    "#000000",
                },
            },
        ],
    },
}
